server:
  port: 8443


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smsDb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123000

mybatis-plus:
  mapper-locations: /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射


jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/smsDb?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: 123000

#mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**/**.xml
entity_package: com.manger.sms.dto